version: '3'
services:
  web:
    build: .
    command: bash -c "rackup config.ru"
    volumes:
      - .:/bitrise-sample-addon
    ports:
      - "3008:4567"
    environment:
      - ADDON_TOKEN=development-token
      - ADDON_SSO_SECRET=development-sso-secret
      - BITRISE_BEAM_VERSION=0.1.6